sudo: required
language: node_js
node_js:
- 5.7.1
env:
  dev:
  - NODE_ENV=TEST
install: npm install
before_script:
- npm install -g gulp
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: gulp test
notifications:
  slack: gitwrecked:OEXOs5wkTZglJKfqGC7edOau
